export const categories = [
  "전체",
  "카페",
  "버거",
  "치킨",
  "피자",
  "편의점",
  "베이커리",
  "뷰티",
] as const;
export type Category = (typeof categories)[number];
export interface Deal {
  id: string;
  brand: string;
  english: string;
  branch: string;
  category: Category;
  mark: string;
  color: string;
  ink?: string;
  title: string;
  subtitle: string;
  benefit: string;
  tag: string;
  distance: number;
  days: number;
  caution: string;
  conditions: string[];
  x: number;
  y: number;
  image: string;
  imageAlt: string;
  url: string;
  stamps?: number;
  coupons: { title: string; expires: string }[];
}
export const deals: Deal[] = [
  {
    id: "starbucks",
    brand: "스타벅스",
    english: "Starbucks",
    branch: "강남역점",
    category: "카페",
    mark: "✦",
    color: "#006341",
    title: "오후의 여유, 아메리카노 1+1",
    subtitle: "친구와 함께, 커피 한 잔 더",
    benefit: "1+1",
    tag: "인기 혜택",
    distance: 120,
    days: 3,
    caution: "오후 2~5시 · 스타벅스 앱 쿠폰 사용 시",
    conditions: [
      "오후 2시부터 5시까지 제조 음료 주문 시 사용",
      "스타벅스 앱 내 이벤트 쿠폰 제시 필수",
      "동일 사이즈 아메리카노에 한해 적용",
      "다른 할인 및 쿠폰과 중복 사용 불가",
    ],
    x: 410,
    y: 390,
    image: "/images/cafe.png",
    imageAlt: "아이스 커피 두 잔과 크루아상",
    url: "https://www.starbucks.co.kr/whats_new/campaign_list.do",
    stamps: 5,
    coupons: [
      { title: "아메리카노 1+1", expires: "09.14" },
      { title: "음료 사이즈 업그레이드", expires: "09.20" },
      { title: "디저트 1,000원 할인", expires: "09.30" },
    ],
  },
  {
    id: "mcdonalds",
    brand: "맥도날드",
    english: "McDonald’s",
    branch: "강남2호점",
    category: "버거",
    mark: "M",
    color: "#ffc72c",
    ink: "#b52222",
    title: "빅맥 세트, 오늘은 30% 할인",
    subtitle: "점심 고민 끝! 든든한 한 끼",
    benefit: "30%",
    tag: "내일 마감",
    distance: 230,
    days: 1,
    caution: "맥도날드 앱 쿠폰 · 1인 1회 사용 가능",
    conditions: [
      "맥도날드 앱 쿠폰을 키오스크 또는 카운터에 제시",
      "매장 방문 및 포장 주문에 한해 사용 가능",
      "배달 주문 제외, 1인 1일 1회 사용",
      "카드사 할인과 중복 적용 여부는 매장 확인 필요",
    ],
    x: 615,
    y: 300,
    image: "/images/burger.jpg",
    imageAlt: "버거와 바삭한 감자튀김",
    url: "https://www.mcdonalds.co.kr/kor/promotion/list",
    coupons: [
      { title: "빅맥 세트 30% 할인", expires: "09.12" },
      { title: "맥너겟 4조각 무료", expires: "09.22" },
    ],
  },
  {
    id: "paris",
    brand: "파리바게뜨",
    english: "Paris Baguette",
    branch: "강남역중앙점",
    category: "베이커리",
    mark: "P",
    color: "#17447e",
    title: "갓 구운 빵과 함께, 최대 20% 할인",
    subtitle: "매일의 작은 행복을 더 가볍게",
    benefit: "20%",
    tag: "카드 혜택",
    distance: 280,
    days: 7,
    caution: "현대카드 결제 · 1만 원 이상 구매 시",
    conditions: [
      "현대카드로 10,000원 이상 결제 시 적용",
      "최대 3,000원 할인, 일부 상품 제외",
      "해피포인트 적립 및 타 쿠폰 중복 불가",
    ],
    x: 305,
    y: 200,
    image: "/images/bakery.jpg",
    imageAlt: "갓 구운 크루아상과 빵",
    url: "https://www.paris.co.kr/promotion/",
    stamps: 3,
    coupons: [{ title: "아침 세트 2,000원 할인", expires: "09.18" }],
  },
  {
    id: "bbq",
    brand: "BBQ",
    english: "BBQ Chicken",
    branch: "역삼스타점",
    category: "치킨",
    mark: "bbq",
    color: "#db3035",
    title: "황금올리브치킨, 포장하면 5천 원",
    subtitle: "오늘 저녁은 바삭하게",
    benefit: "5,000원",
    tag: "포장 할인",
    distance: 360,
    days: 3,
    caution: "자사 앱 포장 주문 · 최소 2만 원 주문",
    conditions: [
      "BBQ 앱에서 포장 주문 시 쿠폰 사용",
      "20,000원 이상 주문 시 5,000원 할인",
      "사이드 메뉴 단독 주문 및 배달 주문 제외",
      "타 행사, 할인 쿠폰과 중복 불가",
    ],
    x: 745,
    y: 435,
    image: "/images/chicken.jpg",
    imageAlt: "노릇하고 바삭한 프라이드치킨",
    url: "https://www.bbq.co.kr/",
    coupons: [{ title: "포장 주문 5,000원 할인", expires: "09.14" }],
  },
  {
    id: "cu",
    brand: "CU",
    english: "CU",
    branch: "강남센트럴점",
    category: "편의점",
    mark: "CU",
    color: "#762d91",
    title: "도시락 + 음료, 든든한 1+1",
    subtitle: "가벼운 지갑을 위한 점심 조합",
    benefit: "1+1",
    tag: "점심 추천",
    distance: 390,
    days: 10,
    caution: "포켓CU 멤버십 · 행사 상품에 한해 적용",
    conditions: [
      "포켓CU 멤버십 바코드 제시",
      "행사 대상 도시락 구매 시 지정 음료 증정",
      "매장 재고 소진 시 조기 종료",
    ],
    x: 220,
    y: 490,
    image: "/images/store.jpg",
    imageAlt: "편의점의 다양한 음료와 간식",
    url: "https://cu.bgfretail.com/event/plus.do?category=event",
    stamps: 7,
    coupons: [{ title: "편의점 1,000원 할인", expires: "09.21" }],
  },
  {
    id: "olive",
    brand: "올리브영",
    english: "Olive Young",
    branch: "강남타운점",
    category: "뷰티",
    mark: "O!",
    color: "#a2c83b",
    ink: "#27381f",
    title: "가을 준비, 인기템 최대 40%",
    subtitle: "나를 위한 작은 선물",
    benefit: "40%",
    tag: "시즌 특가",
    distance: 420,
    days: 1,
    caution: "일부 브랜드 제외 · 행사 상품 한정",
    conditions: [
      "행사 표시 상품에만 할인 적용",
      "온라인몰과 매장 행사 가격은 다를 수 있음",
      "증정품 소진 시 조기 종료",
    ],
    x: 505,
    y: 640,
    image: "/images/beauty.jpg",
    imageAlt: "화장품과 스킨케어 제품",
    url: "https://www.oliveyoung.co.kr/store/main/main.do",
    coupons: [],
  },
  {
    id: "gongcha",
    brand: "공차",
    english: "Gong cha",
    branch: "강남역점",
    category: "카페",
    mark: "貢",
    color: "#b42939",
    title: "밀크티와 펄, 두 배로 즐겨요",
    subtitle: "쫀득한 펄 토핑 무료 추가",
    benefit: "토핑 무료",
    tag: "멤버십",
    distance: 470,
    days: 14,
    caution: "공차 멤버십 · 라지 사이즈 음료 구매 시",
    conditions: [
      "공차 멤버십 적립 회원 대상",
      "라지 사이즈 밀크티 구매 시 펄 1회 무료 추가",
      "일부 시즌 음료 제외",
    ],
    x: 790,
    y: 155,
    image: "/images/tea.jpg",
    imageAlt: "타피오카 펄을 넣은 밀크티",
    url: "https://www.gong-cha.co.kr/brand/content/eventlist?scroll=y",
    stamps: 4,
    coupons: [{ title: "펄 토핑 무료 추가", expires: "09.25" }],
  },
  {
    id: "dominos",
    brand: "도미노피자",
    english: "Domino’s Pizza",
    branch: "역삼점",
    category: "피자",
    mark: "◆",
    color: "#087caf",
    title: "방문포장, 피자 한 판 40% 할인",
    subtitle: "함께 먹으면 더 맛있는 혜택",
    benefit: "40%",
    tag: "포장 할인",
    distance: 550,
    days: 5,
    caution: "온라인 방문포장 · 프리미엄 피자 한정",
    conditions: [
      "공식 홈페이지 또는 앱 방문포장 주문",
      "프리미엄 피자 라지 사이즈에 한정",
      "다른 할인 및 쿠폰과 중복 사용 불가",
    ],
    x: 870,
    y: 600,
    image: "/images/pizza.jpg",
    imageAlt: "페퍼로니 피자",
    url: "https://web.dominos.co.kr/",
    coupons: [],
  },
  {
    id: "twosome",
    brand: "투썸플레이스",
    english: "A Twosome Place",
    branch: "강남역점",
    category: "카페",
    mark: "A",
    color: "#be1833",
    title: "케이크와 아메리카노, 2천 원 할인",
    subtitle: "달콤하게 채우는 오후",
    benefit: "2,000원",
    tag: "디저트 세트",
    distance: 610,
    days: 8,
    caution: "조각 케이크와 음료 함께 구매 시",
    conditions: [
      "조각 케이크와 레귤러 아메리카노 동시 구매",
      "투썸하트 앱 쿠폰 사용 필수",
      "일부 시즌 케이크 제외",
    ],
    x: 640,
    y: 780,
    image: "/images/cafe.png",
    imageAlt: "카페의 커피와 디저트",
    url: "https://www.twosome.co.kr/",
    stamps: 6,
    coupons: [{ title: "케이크 세트 2,000원 할인", expires: "09.19" }],
  },
  {
    id: "gs25",
    brand: "GS25",
    english: "GS25",
    branch: "역삼에이스점",
    category: "편의점",
    mark: "GS",
    color: "#009dc3",
    title: "스낵도 음료도, 골라 담는 2+1",
    subtitle: "퇴근길 작은 즐거움",
    benefit: "2+1",
    tag: "이달의 행사",
    distance: 680,
    days: 19,
    caution: "행사 상품 한정 · 교차 증정 가능 여부 확인",
    conditions: [
      "행사 표기된 동일 상품 3개 구매 시 1개 무료",
      "일부 상품 교차 증정 가능",
      "재고 소진 시 종료",
    ],
    x: 95,
    y: 705,
    image: "/images/store.jpg",
    imageAlt: "편의점의 다양한 음료와 간식",
    url: "https://www.gsretail.com/brand/gs25",
    coupons: [],
  },
];
export const sampleDate = "2026.09.11";
export function endDate(days: number) {
  return `09.${String(11 + days).padStart(2, "0")}`;
}
